unset GREP_OPTIONS

zgen_file="${HOME}/.zgen/zgen.zsh"
if [ ! -f "${zgen_file}" ]; then
    git clone https://github.com/tarjoilija/zgen.git "$(dirname "${zgen_file}")"
fi
source "${zgen_file}"
# if the init scipt doesn't exist
if ! zgen saved; then
    # oh-my-zsh
    zgen oh-my-zsh
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/sudo
    zgen oh-my-zsh plugins/python
    zgen oh-my-zsh plugins/pip
    zgen oh-my-zsh plugins/history
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh themes/agnoster

    # other plugins
    zgen load zsh-users/zsh-syntax-highlighting
    zgen load zsh-users/zsh-history-substring-search
    zgen load sharat87/autoenv
    zgen load rupa/z

    # generate the init script from plugins above
    zgen save
fi

export EDITOR="vim"
export BROWSER="luakit"
export SHELL="zsh"

mkdircd = function(){
    mkdir $1
    cd $1
}

alias ack='ACK_PAGER_COLOR="less -x4SRFX" /usr/bin/ack'
alias others='printf "\33]50;%s%d\007" "xft:Source\ Code\ Pro\ Medium:pixelsize=2"'
