directory: /nas/Music
library: /nas/MusicLibrary.blb

import:
    move: yes
    incremental: yes

match:
    strong_rec_thresh: 0.15

plugins: chroma fetchart

mpd:
    host: runeaudio.lan
    port: 6600
