unset GREP_OPTIONS

zgen_file="${HOME}/.zgen/zgen.zsh"
if [ ! -f "${zgen_file}" ]; then
    git clone https://github.com/tarjoilija/zgen.git "$(dirname "${zgen_file}")"
fi
source "${zgen_file}"
# if the init scipt doesn't exist
if ! zgen saved; then
    # oh-my-zsh
    zgen oh-my-zsh
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/python
    zgen oh-my-zsh plugins/pip
    zgen oh-my-zsh plugins/history
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh themes/agnoster

    # other plugins
    zgen load zsh-users/zsh-syntax-highlighting
    zgen load zsh-users/zsh-history-substring-search
    zgen load rupa/z
    zgen load mollifier/cd-gitroot

    # k will output git style ls
    zgen load supercrabtree/k

    # generate the init script from plugins above
    zgen save
fi

export EDITOR="nvim"
export BROWSER="firefox"
export SHELL="zsh"

mkdircd = function(){
    mkdir $1
    cd $1
}

alias cdg='cd-gitroot'
alias vim='nvim'

alias ack='ACK_PAGER_COLOR="less -x4SRFX" /usr/bin/ack'
alias others='printf "\33]50;%s%d\007" "xft:Source\ Code\ Pro\ Medium:pixelsize=2"'

export ANDROID_HOME=/home/max/Android/Sdk

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# fzf via local installation
if [ -e ~/.fzf ]; then
  PATH=$PATH:~/.fzf/bin
  source ~/.fzf.zsh
  source ~/.fzf/shell/key-bindings.zsh
  source ~/.fzf/shell/completion.zsh
fi

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

if [[ -n "START_COMMAND" ]]; then
  start_command="$START_COMMAND"
  unset START_COMMAND
  eval "$start_command"
fi
